# Generated by Django 3.2.15 on 2022-08-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('example_app', '0002_auto_20220823_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='sex2',
            field=models.CharField(
                blank=True,
                choices=[('Man', 'Man'), ('Female', 'Female'), ('-', '-')],
                max_length=8,
                verbose_name='sex2',
            ),
        ),
    ]
